/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:79cb5d29-1691-43b2-a1d2-cc78a2b2faaf",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_VAj8qO5XM",
    "aws_user_pools_web_client_id": "75299v315cs1otr0o8us5miabj",
    "oauth": {}
};


export default awsmobile;
